import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import ToasterProvider from '@/components/providers/toaster-provider'
import ConfettiProvider from '@/components/providers/confettiProvider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LMS APP',
  description: 'Generated by Abdullah',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body >
          {/* <ConfettiProvider />
          <ToasterProvider /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}